### ISSUE TITLE
Has this work been accepted as any  computer science conference  paper?

### ISSUE THREAD

**Issue by AshiakerWang** [woodyx218/Deep-Learning-with-GDP-Tensorflow#3]
It's no doubt that "deep learning with Gaussian differential privacy" is an excellent work.  I wonder whether there are any plans to submit this paper to  conference of the computer science domain to further increase its influence ?

**Comment by woodyx218** [comment]
Thank you! Our work has been accepted under invited session in the journal, Harvard Data Science Review, https://hdsr.mitpress.mit.edu/pub/u24wj42y/release/1

**Comment by AshiakerWang** [comment]
Thanks for your reply
